
image:
    name: hashicorp/terraform:1.2.1 
    entrypoint: [""]

variables:
    AWS_ACCESS_KEY_ID: ${MY_AWS_ACCESS_KEY}
    AWS_SECRET_ACCESS_KEY: ${MY_AWS_SECRET_ACCESS_KEY}
    AWS_DEFAULT_REGION: "us-east-1"

before_script:
    - terraform --version
    - terraform init

stages:
    - validate
    - plan
    - apply
    - destroy

validate:
    stage: validate
    script:
        - terraform validate

plan:
    stage: plan
    dependencies:
        - validate
    script:
        - terraform plan -out="planfile"
    artifacts:
        paths:
            - planfile

apply:
    stage: apply
    dependencies:
        - plan
    script:
        - terraform apply --input=false "planfile"
    when:
        manual

destroy:
    stage: destroy
    script:
        - terraform destroy -auto-approve
    when:
        manual
